spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/comment
    username: bootuser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #    show-sql: true
        use_sql_comments: true

  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug